application: finddisasterhelp
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /(.*)
  static_files: static/\1
  upload: static/(.*\.(png|html|js|css))

libraries:
- name: webapp2
  version: "2.5.1"
