application: finddisasterhelp
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.appcache)
  static_files: static/\1
  mime_type: text/cache-manifest
  upload: static/(.*\.appcache)

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /(.*)
  static_files: static/\1
  upload: static/(.*\.(png|jpg|html|js|css|ttf))

libraries:
- name: webapp2
  version: "2.5.1"
